#!/bin/bash

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Keymap
setxkbmap -option caps:none
xmodmap "$XDG_CONFIG_HOME/.Xmodmap"

xrandr --output VGA-0 --mode 1360x768 --panning 1700x960 --scale 1.25

# Xresources
xrdb -load "$XDG_CONFIG_HOME/X11/xresources" &

pulseaudio --start &

nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings --load-config-only &

picom &

exec qtile start
