#!/bin/bash

# Keymap
setxkbmap -option caps:none
xmodmap "$XDG_CONFIG_HOME/.Xmodmap"

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xrandr --output VGA-0 --mode 1360x768 --panning 1700x960 --scale 1.25 &
exec qtile start
